"use client";

import { useMemo, useState } from "react";
const score = (checks) => Math.round((checks.filter(Boolean).length / checks.length) * 100);

export default function VisibilityToolsPage() {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [content, setContent] = useState(""); const [imageContext, setImageContext] = useState("");
  const seo = useMemo(() => score([title.length >= 30 && title.length <= 60, description.length >= 120 && description.length <= 160, content.trim().length >= 300, /\b(how|what|why|learn|course|internship)\b/i.test(content)]), [title, description, content]);
  const altText = useMemo(() => { const clean = imageContext.trim().replace(/\s+/g, " "); return clean ? clean.replace(/^(image|photo|picture)\s+(of\s+)?/i, "").replace(/^./, (c) => c.toUpperCase()).slice(0, 125) : ""; }, [imageContext]);
  return <div className="min-h-screen bg-slate-50 px-4 py-12"><section className="mx-auto max-w-5xl"><div className="mb-10 max-w-3xl"><p className="mb-3 text-sm font-semibold uppercase tracking-wider text-blue-700">Free visibility toolkit</p><h1 className="text-4xl font-bold tracking-tight text-slate-900">SEO, GEO & AI-ready content tools</h1><p className="mt-4 text-lg leading-relaxed text-slate-600">Create pages that work for search engines, generative AI answers, and people. Your content stays in this browser.</p></div><div className="grid gap-6 lg:grid-cols-2">
    <ToolCard title="SEO checker" eyebrow={`Score: ${seo}/100`}><Field label={`Page title (${title.length}/60)`} value={title} setValue={setTitle} placeholder="e.g. Digital Marketing Course for LNMU Students" /><Field label={`Meta description (${description.length}/160)`} value={description} setValue={setDescription} placeholder="Describe the page clearly in 120–160 characters." textarea /><p className="text-xs text-slate-500">Aim for a specific title, a useful 120–160 character summary, and at least 300 words of helpful content.</p></ToolCard>
    <ToolCard title="GEO checker" eyebrow="Generative Engine Optimization"><Field label="Paste your page or answer" value={content} setValue={setContent} placeholder="Explain the topic directly. Include who it is for, what they get, and clear facts." textarea /><Checklist values={[[content.length >= 300, "Provides enough useful, self-contained detail"], [/\b(who|students|for)\b/i.test(content), "States who the information is for"], [/\b(what|includes|learn|offer)\b/i.test(content), "Explains the offer or answer directly"], [/\b(week|hour|₹|rs\.?|certificate|online)\b/i.test(content), "Includes concrete facts people can cite"]]} /></ToolCard>
    <ToolCard title="LLM readability" eyebrow="AI answer readiness"><p className="mb-4 text-sm leading-relaxed text-slate-600">LLMs cite clear, factual writing more reliably. Use short paragraphs, answer the main question in the first two sentences, and avoid unsupported claims.</p><Checklist values={[[content.split(/\n|(?<=[.!?])\s+/).filter(Boolean).length >= 3, "Uses multiple short, scannable statements"], [/\b(is|are|includes|offers|learn)\b/i.test(content), "Uses direct, factual language"], [content.length >= 300, "Has enough context for a complete answer"]]} /><p className="mt-5 rounded-lg bg-blue-50 p-3 text-xs text-blue-900">The site also publishes a sitemap and public-page rules for major AI crawlers.</p></ToolCard>
    <ToolCard title="Alt-text generator" eyebrow="Accessible image descriptions"><Field label="What does the image show?" value={imageContext} setValue={setImageContext} placeholder="Students attending a digital marketing workshop in Darbhanga" textarea /><div className="mt-4 rounded-lg border border-dashed border-slate-300 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Suggested alt text</p><p className="mt-2 text-sm text-slate-800">{altText || "Describe the image above to generate concise, useful alt text."}</p></div><p className="mt-3 text-xs text-slate-500">Describe the meaningful content, not “image of”. Keep decorative images empty.</p></ToolCard>
  </div></section></div>;
}
function ToolCard({ title, eyebrow, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">{eyebrow}</p><h2 className="mt-1 text-xl font-bold text-slate-900">{title}</h2><div className="mt-5 space-y-4">{children}</div></section>; }
function Field({ label, value, setValue, placeholder, textarea = false }) { const cls = "w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none transition focus:border-blue-600 focus:ring-2 focus:ring-blue-100"; return <label className="block text-sm font-medium text-slate-700"><span className="mb-1.5 block">{label}</span>{textarea ? <textarea className={`${cls} min-h-24 resize-y`} value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} /> : <input className={cls} value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} />}</label>; }
function Checklist({ values }) { return <ul className="space-y-2">{values.map(([passed, text]) => <li key={text} className={`flex gap-2 text-sm ${passed ? "text-emerald-700" : "text-slate-500"}`}><span>{passed ? "✓" : "○"}</span>{text}</li>)}</ul>; }
